name: deno-test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Lint
        run: deno task lint
      - name: Format
        run: deno task fmt --check
      - name: 'Type check'
        run: deno task check
      - name: 'Test'
        run: deno task test
